services:
  next:
    build: ./next
    volumes:
      - ./next/out:/app/out

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./next/out/build:/html
    ports:
      - "443:443"
    depends_on:
      - next
      # - backend
    networks:
      - internal

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - mysql
    networks:
      - internal

  mysql:
    build: ./mysql
    networks:
      - internal
    env_file:
      - ./.env

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: /data
      type: none
      o: bind

networks:
  internal:
    driver: bridge
