services:
  next:
    build: ./next
    ports:
      - "3000:3000"

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   expose:
  #     - "8080"
  #   depends_on:
  #     - mysql
  #   networks:
  #     - internal

  mysql:
    build: ./mysql
    networks:
      - internal
    # env_file:
    #   - .env
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1235
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: /data
      type: none
      o: bind

networks:
  internal:
    driver: bridge
