services:
  next:
    build: ./next
    volumes:
      - ./next:/app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./next/build:/html
    ports:
      - "443:443"
    depends_on:
      - next
      # - backend
    networks:
      - internal

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   expose:
  #     - "8080"
  #   volumes:
  #     - ./backend:/app
  #   # depends_on:
  #   #   - mysql
  #   networks:
  #     - internal

  # mysql:
  #   build: ./mysql
  #   networks:
  #     - internal

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: /data
      type: none
      o: bind

networks:
  internal:
    driver: bridge
