services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./next/out:/html
    ports:
      - "443:443"
    depends_on:
      - backend
      - next
    networks:
      - internal

  next:
    build: ./next

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
    networks:
      - internal

  mysql:
    build: ./mysql
    networks:
      - internal

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: /data
      type: none
      o: bind

networks:
  internal:
    driver: bridge
